name: CountEntities
main: de.ersterstreber.countentities.Main
version: 1.0
author: erstterstreber
commands:
     countentities:
          description: Zaehlt die Tiere in deinem Chunk.
          aliases: [ce]